### ISSUE TITLE
Incorrect count for: "unit_of_measurement: h"

### ISSUE THREAD

**Issue by home409ca** [danieldotnl/ha-measureit#55]
### System Health details

Core 2023.12.4
Supervisor 2023.12.0
Operating System 11.2
Interfejs użytkownika 20231208.2

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/danieldotnl/ha-measureit/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

When selecting the unit of measurement "h", it counts hours incorrectly.

![image](https://github.com/danieldotnl/ha-measureit/assets/114701129/596265c3-015d-4142-b2d4-e3d82ce34a7e)

![image](https://github.com/danieldotnl/ha-measureit/assets/114701129/112730a8-7ca5-4016-8311-93943e6d0bf0)

Manually (not using ha-measureit) works fine:

![image](https://github.com/danieldotnl/ha-measureit/assets/114701129/777b823b-d307-4014-b39a-e475e66ab525)

![image](https://github.com/danieldotnl/ha-measureit/assets/114701129/8270172f-f205-40a2-b78d-478ea0cb7fc6)

### Reproduction steps

Time meter.
Template: {{is_state('binary_sensor.sm_g991b', 'off')}}

### Debug logs

```text
n/a
```

**Comment by danieldotnl** [comment]
But did you also set the value template to divide the value by 3600?

**Comment by home409ca** [comment]
Can you tell me what to enter in the "Value template"?
I don't know how to react to the result.

Can you give an example?

Thanks

**Comment by danieldotnl** [comment]
[{{ (states('sensor.my,sensor_day') | float / 3600) | round(2) }}](https://community.home-assistant.io/t/measureit-measure-all-you-need-based-on-time-and-templates/660614/2?u=danieldotnl)

**Comment by home409ca** [comment]
Still counts in seconds...

Below is the recording.
I used templates:
{{ is_state('switch.kitchen_light_left', 'on') }}
{{ (states('sensor.my,sensor_day') | float / 3600) | round(2) }}

and units: h


https://github.com/danieldotnl/ha-measureit/assets/114701129/780bb75c-8a65-46f3-ab6e-ba53d664d4f4

**Comment by danieldotnl** [comment]
Sorry, you are right. I just copied the reply from the forum without testing.
Couple of remarks:
- the right value_template should be something like `{{ value | float / 3600 }}`. It should not get the state from the states function as this contains the previous value of the sensor.
- Even with the right template, it might not do what you expect, and because this is the behaviour when assigning the device_class 'duration'. Device classes influence how the frontend displays data. And I think it does a nice job when you just keep it in seconds. When the value is low, it displays seconds or minutes and when higher, it changes into hours.
- If you really want a specific format, I think you should create a new config without the device_class (I just found a bug that updating the device_class in the options menu doesn't work). You can then do something like [mentioned in this thread.](https://community.home-assistant.io/t/solved-convert-seconds-in-mm-ss/446476/2)

Hope this helps!!

**Comment by andersonthomas** [comment]
Hi, can u pls enter here how can i change measuring from seconds to hours ? im total programming noob, so i would appreciate to have a code for that. thanks

**Comment by danieldotnl** [comment]
It doesn't work in the current version. I'm working on a new one.
When measuring in hours, what format would you expect/what would the sensor state look like?

**Comment by andersonthomas** [comment]
24h format, so for example 14:37h  ;-) thanks

**Comment by danieldotnl** [comment]
Please upgrade to v0.5.4 and read the rewritten README after formatting time sensors.
