### ISSUE TITLE
I just can't get it to work

### ISSUE THREAD

**Issue by josephny** [danieldotnl/ha-measureit#64]
I've been trying, but I just can't get it to work.

I have 2 binary sensors:

  binary_sensor.125_1st_fl_heat_graph_binary
  binary_sensor.125_2nd_fl_heat_graph_binary

And I would like to maintain a daily total of the number of minutes when either state is ON.

I admit I don't even understand if I should choose TIME or SENSOR for that which I want to measure.  I tried both.

I don't understand when to use a condition template vs. a value template.

I understand that there is a lot I don't understand, but I had high hopes this integration would make it easy enough for a total non-programmer to make work.

Any help would be appreciated.

Thank you.

**Comment by danieldotnl** [comment]
First of all, be aware that I'm currently rewriting this integration as it contains some important issues (like resetting at midnight UTC instead of midnight in the server timezone).
Secondly, you kind of need to be able to work with templates in Home Assistant to be able to use this integration.

That being said, you want to measure time, so choose time from the menu. Then try this as the condition:
```{{ is_state('binary_sensor.125_1st_fl_heat_graph_binary', 'on') or is_state('binary_sensor.125_2nd_fl_heat_graph_binary', 'on') }}```

**Comment by josephny** [comment]
Thank you very much.  I think it is working.
